#Project Info
info:
  app:
    name: Config Server
    description: Config Server
    version: 0.0.1

server:
  port: 15990

spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/oshnew/msa-cofig-server-study-repo.git"
          skip-ssl-validation: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.12:3306/config_server
      username: test-user
      password: Test-password-1@
